version: 0.2
env:
  secrets-manager:
    AWS_KEY_ID: AppDeploy2
phases:
  install: # Install AWS cli, kubectl and Helm3
    commands:
       - apt-get update
       - apt-get install -y git python3 python3-pip
       - pip install awscli
       - curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
       - chmod +x ./aws-iam-authenticator
       - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
       - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
       - chmod +x kubectl
       - mv ./kubectl /usr/local/bin/kubectl
       - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
       - helm repo add stable https://charts.helm.sh/stable && helm repo update

  pre_build: # Check helm version and Add kubeconfig to access to EKS cluster and check readiness of the cluster
    commands:
      - chmod +x ./aws-cicd/scripts/setup.sh
      - ./aws-cicd/scripts/setup.sh

  
  build: # Deploy app via Helm
    commands:
      - chmod +x ./aws-cicd/scripts/deploy.sh
      - ./aws-cicd/scripts/deploy.sh
  
  post_build: # Display the endpoint of the application
    commands:
      - chmod +x ./aws-cicd/scripts/check.sh
      - ./aws-cicd/scripts/check.sh